// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_6O4pKV2bOrXBYnBzqUixHpMugHcjkXs',
    appId: '1:204554823183:web:97428c5d196c0d2061657a',
    messagingSenderId: '204554823183',
    projectId: 'resident-society',
    authDomain: 'resident-society.firebaseapp.com',
    storageBucket: 'resident-society.appspot.com',
    measurementId: 'G-HCBEG15SGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaKvMgEp0R3XLvBrE3zeOV5YDLoZGbYbc',
    appId: '1:204554823183:android:265071a213b64dec61657a',
    messagingSenderId: '204554823183',
    projectId: 'resident-society',
    storageBucket: 'resident-society.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MZCyPUxVSPnVeO0uu775UhXh_zWp7qU',
    appId: '1:204554823183:ios:570b6678e6996a8261657a',
    messagingSenderId: '204554823183',
    projectId: 'resident-society',
    storageBucket: 'resident-society.appspot.com',
    iosBundleId: 'com.resident.resident',
  );
}
